name = "nostal-optimization"
author = "Nostal Yuu"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b9fabb2eaad95cd75538b70882837a203931bca399189292a791cb29184da5bb"

[versions]
fabric = "0.15.11"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
