name = "nostal-optimization"
author = "Nostal Yuu"
version = "1.3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "110efac0c7f5a6f00f98514b4516e234bb940757136ddb368eb8757e61c39964"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21.3", "1.21.4-pre1"]
