name = "nostal-optimization"
author = "Nostal Yuu"
version = "1.2.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db60dc73a58ee064b8296dfbd28775216cab996bc76d4d84d4578d890d161b72"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"
