name = "nostal-optimization"
author = "Nostal Yuu"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d0eb03888ee34d971eb08a2d4531bd64aa29a5e73759f7d84e7e73c63a0ddfe5"

[versions]
fabric = "0.15.11"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
