name = "nostal-optimization"
author = "Nostal Yuu"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "43b57924a3a374c041f0d06d8420388854b1fd08c7fee5f6516f1ca9eaa07730"

[versions]
fabric = "0.15.11"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
