name = "nostal-optimization"
author = "Nostal Yuu"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0cd7b044b4865709614056732bcbed41fc280e1cf58798e3700ae6a1a7fe26fc"

[versions]
fabric = "0.15.11"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
