name = "nostal-optimization"
author = "Nostal Yuu"
version = "1.2.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2dacf7d323a38527be4f4be2360f38ee8e7446dfe8c2265b9d91217c8cbefe66"

[versions]
fabric = "0.15.3"
minecraft = "1.20.4"
