name = "nostal-optimization"
author = "Nostal Yuu"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3faacddf746c52ce73c01e57da391923f6081812aba51576cf95b01f97f36be6"

[versions]
fabric = "0.15.11"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
